name: Batboy CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv and dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          .\.venv\Scripts\activate 2>$null || source .venv/bin/activate
          uv pip install -e .[dev]

      - name: Run tests (excluding web)
        run: |
          .\.venv\Scripts\activate 2>$null || source .venv/bin/activate
          pytest -m "not web"
