name: Batboy CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            pytest_cmd: .venv/bin/python -m pytest
          - os: windows-latest
            pytest_cmd: .venv\Scripts\python -m pytest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv and dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          uv pip install -e .[dev]

      - name: Run tests (excluding web)
        run: ${{ matrix.pytest_cmd }} -m "not web"
