# src/batboy/config/constants.py

STAT_CATEGORY_SCHEMAS = {
    "hitting": [
        "Date",
        "Opponent",
        "Result",
        "R",
        "AB",
        "H",
        "2B",
        "3B",
        "TB",
        "HR",
        "RBI",
        "BB",
        "HBP",
        "SF",
        "SH",
        "K",
        "OPP DP",
        "CS",
        "Picked",
        "SB",
        "IBB",
        "GDP",
        "RBI2out",
    ],
    "pitching": [
        "Date",
        "Opponent",
        "Result",
        "App",
        "ERA",
        "IP",
        "CG",
        "H",
        "R",
        "ER",
        "BB",
        "SO",
        "SHO",
        "BF",
        "P-OAB",
        "2B-A",
        "3B-A",
        "Bk",
        "HR-A",
        "WP",
        "HB",
        "IBB",
        "Inh Run",
        "Inh Run Score",
        "SHA",
        "SFA",
        "Pitches",
        "GO",
        "FO",
        "W",
        "L",
        "SV",
        "KL",
        "pickoffs",
    ],
    "fielding": [
        "Date",
        "Opponent",
        "Result",
        "PO",
        "A",
        "TC",
        "E",
        "FldPct",
        "CI",
        "PB",
        "SBA",
        "CSB",
        "IDP",
        "TP",
        "SBAPct",
    ],
}

# Minimal set of common numeric columns (safe to cast as int or float)
INT64_COLUMNS = {
    "R",
    "AB",
    "H",
    "2B",
    "3B",
    "TB",
    "HR",
    "RBI",
    "BB",
    "HBP",
    "SF",
    "SH",
    "K",
    "OPP DP",
    "CS",
    "Picked",
    "SB",
    "IBB",
    "GDP",
    "RBI2out",
    "App",
    "CG",
    "ER",
    "SO",
    "BF",
    "2B-A",
    "3B-A",
    "Bk",
    "HR-A",
    "WP",
    "HB",
    "Inh Run",
    "Inh Run Score",
    "SHA",
    "SFA",
    "Pitches",
    "GO",
    "FO",
    "W",
    "L",
    "SV",
    "KL",
    "pickoffs",
    "PO",
    "A",
    "TC",
    "E",
    "CI",
    "PB",
    "SBA",
    "CSB",
    "IDP",
    "TP",
}

FLOAT32_COLUMNS = {"FldPct", "SBAPct", "ERA", "OBPct", "SlgPct", "BA", "IP", "win_pct"}
